name: Ocarina / Ubuntu latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain (Ubuntu default distribution)
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - name: Set up ocarina-builder
      run: >
       git clone https://github.com/OpenAADL/ocarina-build.git

    - name: Build
      run: ( cd ocarina-build ; ./build_ocarina.sh --scenario=travis-ci )
